# Generated by Django 3.2.11 on 2022-01-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('date', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('copyright', models.CharField(blank=True, db_index=True, max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('hdurl', models.URLField()),
                ('media_type', models.CharField(blank=True, db_index=True, max_length=200)),
                ('service_version', models.CharField(blank=True, db_index=True, max_length=200)),
                ('raw_api_response', models.JSONField(default=dict)),
                ('created_ts', models.DateTimeField(auto_now_add=True, help_text='When the entry was added')),
                ('updated_ts', models.DateTimeField(auto_now=True, db_index=True, help_text='When the entry was last updated')),
            ],
            options={
                'verbose_name': 'APOD',
                'verbose_name_plural': 'APODs',
            },
        ),
        migrations.AddIndex(
            model_name='apod',
            index=models.Index(fields=['date'], name='nasa_apod_date_f9ab6c_idx'),
        ),
    ]
